# Generated by Django 4.0.4 on 2022-04-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name': 'Accounts', 'verbose_name_plural': 'Accounts'},
        ),
    ]
